version: '3.8'

services:
  backend:
    build: ./backend
    container_name: control-sys-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads   # Salva as imagens na sua pasta local
      - sqlite_data:/app/data            # Volume gerenciado para o banco
    environment:
      - DATABASE_URL=sqlite:///./data/estoque.db
    # Sobrescreve o comando para garantir que o DB fique na pasta do volume
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ./frontend
    container_name: control-sys-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  sqlite_data: